"""Turn a portrait photo into a compact 3D point cloud (the photo itself is never shipped).

usage: python3 scripts/face-points.py path/to/photo.jpg > src/data/face-points.js
Output: base64 of N * 4 bytes -> int8 x, int8 y, int8 z, uint8 tone.
Tuned for a centered, front-facing portrait on a light background.
"""
import sys, base64
import numpy as np
from PIL import Image, ImageFilter

rng = np.random.default_rng(7)
img = Image.open(sys.argv[1]).convert('RGB').resize((500, 500), Image.LANCZOS)
a = np.asarray(img).astype(np.float32) / 255
lum = a @ np.array([0.299, 0.587, 0.114])
fg = (1 - a.min(axis=2)) > 0.12                        # not near-white background
fg = np.asarray(Image.fromarray((fg * 255).astype(np.uint8)).filter(ImageFilter.MinFilter(3))) > 0
H, W = lum.shape
yy, xx = np.mgrid[0:H, 0:W]
fg &= yy < 470                                         # trim bottom edge

# tone: local contrast so features read on any skin tone
blur = np.asarray(Image.fromarray((lum * 255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(14))) / 255
lo, hi = np.percentile(lum[fg], [3, 97])
tone = np.clip(((lum - lo) / (hi - lo)) * 0.75 + (lum - blur) * 2.5 + 0.1, 0, 1)
gx = np.abs(np.diff(lum, axis=1, append=lum[:, -1:]))
gy = np.abs(np.diff(lum, axis=0, append=lum[-1:, :]))
edge = np.clip((gx + gy) * 6, 0, 1)

# depth prior: head ellipsoid + nose/brow/lips bumps, body plane behind
cx, cy = 250, 225
dx, dy = (xx - cx) / 125, (yy - cy) / 165
head = np.sqrt(np.clip(1 - dx**2 - dy**2, 0, 1))
g = lambda x0, y0, sx, sy: np.exp(-(((xx - x0) / sx) ** 2 + ((yy - y0) / sy) ** 2))
z = head * 0.75 + g(255, 235, 16, 34) * 0.32 + g(255, 268, 26, 12) * 0.12 + g(255, 275, 30, 10) * 0.08 \
    - g(210, 195, 24, 12) * 0.06 - g(295, 195, 24, 12) * 0.06
body = (yy > 340) & (head == 0)
z = np.where(body, 0.15 - np.abs(xx - cx) / 600, z)
z = np.where((head == 0) & ~body, 0.2, z)              # ears / hair outskirts

ys, xs = np.nonzero(fg)
w = 0.15 + edge[ys, xs] * 2.5 + (head[ys, xs] > 0) * 0.9
pick = rng.choice(len(xs), size=min(7000, len(xs)), replace=False, p=w / w.sum())
xs, ys = xs[pick] + rng.random(len(pick)) - 0.5, ys[pick] + rng.random(len(pick)) - 0.5
xi, yi = xs.astype(int).clip(0, W - 1), ys.astype(int).clip(0, H - 1)

X = np.clip((xs - cx) / 250 * 127, -127, 127)
Y = np.clip((ys - 240) / 250 * 127, -127, 127)
Z = np.clip((z[yi, xi] - 0.4) * 127, -127, 127)
T = np.clip(tone[yi, xi] * 0.85 + edge[yi, xi] * 0.15, 0, 1) ** 1.2 * 255
buf = np.stack([X, Y, Z]).T.astype(np.int8).tobytes()
out = bytearray()
for i in range(len(pick)):
    out += buf[i*3:i*3+3] + bytes([int(T[i])])
print('// Generated by scripts/face-points.py — 3D point cloud (x,y,z int8, tone uint8). No photo is shipped.')
print(f"export const FACE_POINTS = '{base64.b64encode(bytes(out)).decode()}';")
